### ISSUE TITLE
How to set start first week day?

### ISSUE THREAD

**Issue by yothin** [LumenSpark/LSWeekView#2]
I want to set start week day in Monday . how to do it

Thank you
Yohtin

**Comment by chrisze** [comment]
Just set the `LSWeekView` `calendar` property on the `NSCalendar` instance with `firstWeekDay` adjusted accordingly. Normally you shouldn't need to do anything, if the default calendar is set properly.

**Comment by yothin** [comment]
Thank you @chrisze
